apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "terminal.labels" . | nindent 4 }}
  name: {{ include "terminal.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "terminal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "terminal.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: "{{ .Values.image }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: IfNotPresent
        name: terminal
        command:
        - /usr/local/bin/gotty
        - --permit-write
        - --reconnect
        - /bin/bash
        ports:
        - containerPort: {{ .Values.port }}
          protocol: TCP
        resources:
        {{- .Values.resources | toYaml | nindent 10 }}
      securityContext: {}
      terminationGracePeriodSeconds: 1
