# Default values for ack-tensorflow-dev.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jupyter:
  image:
    repository: tensorflow/tensorflow
    tag: 1.12.0-devel-py3
    pullPolicy: Always
  password: okteto
tensorboard:
  image:
    repository: tensorflow/tensorflow
    tag: 1.12.0-devel-py3
    pullPolicy: Always
service:
  type: ClusterIP
