# available runtimes: go, python, dart, cpp, java, rust, nodejs
runtime: nodejs

# This is the port that Theia is running on. Change this if you want to use this port instead
service:
  port: 3000 # Default Theia port
  
# use this to clone a public repository automatically
repository: https://github.com/okteto/movies

# set this when using a private repository https://github.com/settings/tokens
# or add a GIT_TOKEN okteto secret
gitToken:

persistence:
  size: 1Gi

resources:
  limits:
    cpu: "1"
    memory: 2Gi
