# Default values for okteflix.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  pullPolicy: Always

ingress:
  annotations: {}

replicaCount: 1
resources: {}

mongodb:
  usePassword: true
  mongodbUsername: okteto
  mongodbDatabase: okteto 
  mongodbPassword: "okteto" 